### ISSUE TITLE
Generated site has localhost:1313 as the host for all static files

### ISSUE THREAD

**Issue by gargs** [xaviablaza/hugo-lodi-theme#10]
Perhaps I am doing something wrong, but the generated website seems to have a 'localhost:1313' prefix for all static files. 

eg: `<meta name="twitter:image" content="localhost:1313img/portfolio.jpg">`

PS: Amazing theme; thanks! 🙂

**Comment by xaviablaza** [comment]
Did you change the `baseURL` in `config.toml`?

Thank you!

**Comment by gargs** [comment]
Ah, 🤦‍♂️

That was it. Thanks!
