### ISSUE TITLE
The page build failed for the `master` branch with the following error

### ISSUE THREAD

**Issue by SaminYeasar** [xaviablaza/hugo-lodi-theme#12]
Hi,

I'm getting the following issue, can't figure out what to alter. 
"Your site is having problems building: The value '{}' was passed to a date-related filter that expects valid dates in /_layouts/default.html or one of its layouts. For more information,"

**Comment by xaviablaza** [comment]
What Hugo version are you using, and do you have a fork I can look at with
your code?

**Comment by SaminYeasar** [comment]
Hi, I'm using the Hugo version of v0.74.3. Here's the code repo: https://github.com/SaminYeasar/saminyeasar.github.io

**Comment by xaviablaza** [comment]
Great, I will get back to you when I investigate the problem. Please do
update if you happen to find a solution!

**Comment by xaviablaza** [comment]
Hi @SaminYeasar, thank you for your patience, I was able to investigate this further. The theme works on `v0.74.3`. You need to run `hugo` and serve the site from the `public` folder.

I recommend hosting the site on Netlify or Render for this purpose instead of on GitHub Pages.
