### ISSUE TITLE
Resonsible navigation?

### ISSUE THREAD

**Issue by paichinger** [xaviablaza/hugo-lodi-theme#9]
Hey!
I really like this theme. I want to use it for my portfolio too. I already started, now I noticed that the navigation is not really responsible. Are there any plans to change that?
Otherwise I'd unfortunately would need to switch to a different theme, as responsibility is a must for me.
Regards,
Peter

**Comment by xaviablaza** [comment]
Hi Peter, could you please provide a screenshot of where the navigation is not responsive and the browser you're using?

**Comment by xaviablaza** [comment]
Stale issue; closing.
